In [17]:
from model import Fitness

# Data visualization tools.
import seaborn as sns
import seaborn.objects as so
import numpy as np
import pandas as pd
import janitor
import matplotlib.pyplot as plt

import altair as alt
alt.data_transformers.enable("vegafusion")
alt.renderers.enable("jupyter", offline=True)

RendererRegistry.enable('jupyter')

In [2]:
model = Fitness(200, 20, 20, abundance=0.25, mutation=False, choosy=True)

for _ in range(10000):
    model.step()

model_data = model.datacollector.get_model_vars_dataframe()
model_agent_data = model.datacollector.get_agent_vars_dataframe()

In [4]:
agent_pops = model_data.drop(columns=['Avg Fitness', 'Population']).reset_index().rename(columns={'index': 'step'})

agent_pops.head()

,step,carrier_none_pop,carrier_choosy_pop,giver_none_pop,carrier_none_births,carrier_none_deaths,carrier_choosy_births,carrier_choosy_deaths,giver_none_births,giver_none_deaths
0,0,50,50,100,50,0,50,0,100,0
1,1,50,50,100,0,0,0,0,0,0
2,2,50,50,100,0,0,0,0,0,0
3,3,50,50,100,0,0,0,0,0,0
4,4,50,50,100,0,0,0,0,0,0

In [26]:
agent_pops_long = agent_pops.pivot_longer(index='step',
                                          names_to=('role', 'strategy', 'stat'),
                                          names_sep='_')

agent_pops_long

        step     role strategy    stat  value
0          0  carrier     none     pop     50
1          1  carrier     none     pop     50
2          2  carrier     none     pop     50
3          3  carrier     none     pop     50
4          4  carrier     none     pop     50
...      ...      ...      ...     ...    ...
90004   9996    giver     none  deaths      0
90005   9997    giver     none  deaths      1
90006   9998    giver     none  deaths      0
90007   9999    giver     none  deaths      0
90008  10000    giver     none  deaths      0

[90009 rows x 5 columns]

In [33]:
alt.Chart(agent_pops_long.loc[agent_pops_long['stat'] == 'pop']).mark_line(
).encode(
    alt.X('step:T'),
    alt.Y('value:Q'),
    color='role:N',
    strokeDash='strategy:N'
).properties(
    width=800
)

JupyterChart()